version: '3'

services:
  app:
    image: bt-reviewer:latest
    container_name: bt-reviewer
    build: .
    command: 
    stdin_open: true
    tty: true
    environment:
      - OPENAI_API_KEY=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
